name: Run Maestro Android Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-android-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | MAESTRO_INSTALL_FORCE_PLATFORM=linux bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Upload APK to Maestro Cloud
        id: upload
        run: |
          APP_URL=$(maestro upload-app heymax.apk)
          echo "app_url=$APP_URL" >> $GITHUB_OUTPUT

      - name: Run Maestro Test
        run: |
          maestro test --api-url ${{ steps.upload.outputs.app_url }} flows/
